# Project-specific R8 rules (release build, isMinifyEnabled = true).

# --- Stack traces: keep line numbers so the in-app crash dialog stays readable.
-keepattributes SourceFile,LineNumberTable,*Annotation*,Signature,InnerClasses,EnclosingMethod
-renamesourcefileattribute SourceFile

# --- JGit: reaches config/transport/text-bundle classes reflectively (JGitText fields,
# ServiceLoader entries, enum-by-name lookups).
-keep class org.eclipse.jgit.** { *; }
-keep interface org.eclipse.jgit.** { *; }
-dontwarn org.eclipse.jgit.**
# JGit optional / non-Android references that are never hit at runtime.
-dontwarn com.googlecode.javaewah.**
-dontwarn com.jcraft.jsch.**
-dontwarn org.apache.sshd.**
-dontwarn org.ietf.jgss.**
-dontwarn javax.management.**
-dontwarn java.lang.management.**
-dontwarn java.lang.ProcessHandle
-dontwarn com.sun.jna.**
-dontwarn org.slf4j.**
-dontwarn org.bouncycastle.**

# --- Sora Editor + TextMate (tm4e, joni, jcodings, gson).
# SelectionPopupLabels.kt maps popup buttons by Sora *field names* via reflection, and
# SelectionPopup.kt calls Sora getters reflectively -> names must not be obfuscated.
-keep class io.github.rosemoe.sora.** { *; }
-keep interface io.github.rosemoe.sora.** { *; }
-keep class org.eclipse.tm4e.** { *; }
-keep class org.joni.** { *; }
-keep class org.jcodings.** { *; }
-keep class com.google.gson.** { *; }
-dontwarn io.github.rosemoe.sora.**
-dontwarn org.eclipse.tm4e.**
-dontwarn org.joni.**
-dontwarn org.jcodings.**
-dontwarn com.google.gson.**

# --- AndroidSVG (parsed via reflection-free API, but keep to be safe with its SAX handlers).
-keep class com.caverock.androidsvg.** { *; }
-dontwarn com.caverock.androidsvg.**

# --- OkHttp / Okio optional TLS providers (consumer rules cover most; these silence the rest).
-dontwarn org.conscrypt.**
-dontwarn org.openjsse.**
-dontwarn okhttp3.internal.platform.**

# --- WebView JS bridges: annotated methods must survive.
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

# --- Room: entities/DAOs are generated by KSP and carry their own consumer rules; keep
# our entity classes so column names are never renamed.
-keep class com.invictus.xcode.core.data.** { *; }
